[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multilingual_transformer"
version = "0.1.0"
description = "High-performance PyTorch multilingual transformer trained from scratch for Indic languages"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "tokenizers",
    "datasets",
    "sacrebleu",
    "numpy",
    "tqdm",
    "ipywidgets",
    "tomli",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["multilingual_transformer*"]

[tool.setuptools.package-data]
multilingual_transformer = ["configs/*.toml"]

[tool.pylint.messages_control]
disable = ["all"]
enable = [
    "syntax-error",
    "unexpected-keyword-arg",
    "no-value-for-parameter",
    "too-many-function-args",
    "undefined-variable"
]


[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
explicit_package_bases = true
disable_error_code = [
    "import-untyped",
    "annotation-unchecked",
    "return-value",
    "index",
    "assignment",
    "union-attr",
]