[project]
name = "multilingual_transformer"
seed = 42

[language_map]
English      = "en"
Hindi        = "hi"
Marathi      = "mr"
Bengali      = "bn"
Gujarati     = "gu"
Kannada      = "kn"
Malayalam    = "ml"
Odia         = "or"
Punjabi      = "pa"
Tamil        = "ta"
Telugu       = "te"
Assamese     = "as"
Sanskrit     = "sa"
Multilingual = "multi"

[language]
src_lang = "Multilingual"
target_lang = "Multilingual"
dataset_name = "multilingual_blend"

[dataset_map]
hi = "ai4bharat/samanantar"
mr = "ai4bharat/samanantar"
bn = "ai4bharat/samanantar"
gu = "ai4bharat/samanantar"
kn = "ai4bharat/samanantar"
ml = "ai4bharat/samanantar"
or = "ai4bharat/samanantar"
pa = "ai4bharat/samanantar"
ta = "ai4bharat/samanantar"
te = "ai4bharat/samanantar"
as = "ai4bharat/samanantar"
sa = "acomquest/Saamayik"

[multilingual]
train_languages_pairs = ["en-hi", "en-mr", "en-sa"]
target_tokens_format = "<2{}>"
pairs_per_lang = 50000
val_size_per_lang = 5000
test_size_per_lang = 5000

[data]
data_dir = "processed_multi_data"
checkpoint_dir = "checkpoints_multi"
tokenizer_dir = "processed_multi_tokenizers"
train_size = 300000  # Dummy value for AppConfig compatibility
val_size = 15000
test_size = 15000
max_len = 96
max_length_ratio = 5.0
force_download = false

[tokenizer]
algo_src = "wordpiece"
algo_tgt = "unigram"
max_vocab_size = 24000

[model]
d_model = 256
num_layers = 4
num_heads = 4
d_ff = 768
dropout = 0.1

[training]
epochs = 10
batch_size = 256
lr = 5.0e-4
weight_decay = 0.01
label_smoothing = 0.1
torch_compile = false
gen_batch_size = 256
bleu_sample = 1000
save_best = true

[inference]
no_repeat_ngram_size = 3
sample_source = "config"
num_samples = 4
sample_sentences = ["farmer is important to the country", 
"hi: education is essential for every child",
"mr: education is essential for every child",
"sa: education is essential for every child"]